### ISSUE TITLE
NPE in AnnotationProcessor

### ISSUE THREAD

**Issue by cbruegg** [koesie10/ormlite-processor#6]
```
        at com.koenv.ormlite.processor.AnnotationProcessor.getFieldConfig(AnnotationProcessor.java:286)
        at com.koenv.ormlite.processor.AnnotationProcessor.generateFile(AnnotationProcessor.java:199)
        at com.koenv.ormlite.processor.AnnotationProcessor.process(AnnotationProcessor.java:119)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 34 more
```

Would it be safe to simply insert a null check in line 286 and not execute the statement if the persister class is null? In that case, I could submit a quick PR.

**Comment by cbruegg** [comment]
Hi @koesie10, just checking you didn't miss this?

**Comment by koesie10** [comment]
Thanks, I totally missed it.

Could you please post an example of a class that gives this exception because technically the persister class can never be null as far as I can see.

**Comment by cbruegg** [comment]
Looks like it's due to this field in a class called `Note`:

```
    @ForeignCollectionField(eager = false)
    private ForeignCollection<NotePlantAction> notePlantActions;
```

The class `NotePlantAction` seems to be generated after `Note`, if that matters.

If you can't reproduce, I'll create a small sample project.

**Comment by koesie10** [comment]
Thanks for the report!
